#!/usr/bin/env bash
# Move this to devship
echo "Install Traefik using Helm"
helm repo add traefik https://traefik.github.io/charts
helm repo update
echo -n "Enter Traefik Dashboard password [nurrony]: "
read -s TRAEFIK_DASHBOARD_PASS
TRAEFIK_DASHBOARD_PASS=${TRAEFIK_DASHBOARD_PASS:-nurrony}
helm install traefik traefik/traefik --namespace kube-system --wait -f - <<EOF
# Create an IngressRoute for the dashboard
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(\`traefik.nurrony.localhost\`)
    entryPoints: ["websecure"]
    middlewares:
      - name: traefik-dashboard-auth

tlsStore:
  default:
    defaultCertificate:
      secretName: devship-service-certs

extraObjects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: traefik-dashboard-auth-secret
    type: kubernetes.io/basic-auth
    stringData:
      username: admin
      password: nurrony

  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: traefik-dashboard-auth
    spec:
      basicAuth:
        secret: traefik-dashboard-auth-secret
  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: traefik-redirect-https
    spec:
      redirectScheme:
        scheme: https
        permanent: true
EOF
