apiVersion: v1
kind: ServiceAccount
metadata:
  name: headlamp-admin
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: headlamp-admin
  namespace: kube-system

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: my-headlamp-ingress
  namespace: kube-system
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`headlamp.<your-cluster-fqdn>`)
      kind: Rule
      middlewares:
        - name: traefik-redirect-https
      services:
        - name: my-headlamp
          port: 80
  tls: {} # cluster comes with defaultTlsStore
