# Create an IngressRoute for the dashboard
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.nurrony.localhost`)
    entryPoints: ["websecure"]
    middlewares:
      - name: traefik-dashboard-auth

tlsStore:
  default:
    defaultCertificate:
      secretName: devship-service-certs

extraObjects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: traefik-dashboard-auth-secret
    type: kubernetes.io/basic-auth
    stringData:
      username: admin
      password: nurrony

  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: traefik-dashboard-auth
    spec:
      basicAuth:
        secret: traefik-dashboard-auth-secret
